### PR TITLE
Suppress "ReplaceInFile" temporary topfind.old

### PR DESCRIPTION
**Pull request by ttamttam**
Allow a full uninstall if OCaml/ directory was not added any other file.

### CODE REVIEW

**Comment by msprotz** [comment]
Does the installer install this file?

A more general fix would be something like "there are still files in there that were not installed by the installer; do you still wish to remove the c:\ocaml directory?". Don't know if you know how to do that... :)

**Comment by ttamttam** [comment]
Le 29/10/2015 20:49, Jonathan Protzenko a écrit :
>
> Does the installer install this file?
>

Yes. This is done during the string replacements in topfind, at
installation time.
Hence the proposed Deletion just after topfind was adjusted.

> A more general fix would be something like "there are still files in
> there that were not installed by the installer; do you still wish to
> remove the c:\ocaml directory?". Don't know if you know how to do
> that... :)
>




Another adaptation I had to do in order to be able to work was this, at
the same place:

AccessControl::GrantOnFile "$INSTDIR\lib\topfind" "(S-1-5-32-545)"
"FullAccess"

Before I did that, I was not able too use topfind in the toplevel. But
this may be related to the long history of the cygwin I'm using.

Salutations

-- 
Matthieu Dubuget
Guide d’autodéfense numérique : http://guide.boum.org

**Comment by msprotz** [comment]
Thanks for the explanations. I haven't seen anyone else report issues with topfind; if someone else has the problem, I'll integrate your fix. Thanks!

**Comment by ttamttam** [comment]
Thanks. I think the problem does not appear often: since everybody
install camlfind packages in c:/OCaml, the second problem you pointed
out is more likely to happen…

Le 29/10/2015 21:01, Jonathan Protzenko a écrit :

> Thanks for the explanations. I haven't seen anyone else report issues
> with topfind; if someone else has the problem, I'll integrate your
> fix. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/protz/ocaml-installer/pull/34#issuecomment-152302566.

## 

Matthieu Dubuget
Guide d’autodéfense numérique : http://guide.boum.org

**Pull request merged**
